add: Frame classes, Controllers, Tests
SergeyMont/java-filmorate pull request #2
Opened 2022-04-25 18:01 UTC by SergeyMont

2022-04-25 21:05 UTC, kukolev requested changes

2022-04-25 21:05 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Нарушение кодстайла: Лишние отступы перед кодом. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-04-25 21:05 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        //final Exception exception= assertThrows(MethodArgumentNotValidException.class, () ->
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-04-26 18:14 UTC, SergeyMont commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
fix

2022-04-26 18:14 UTC, SergeyMont commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
fix

2022-04-26 18:21 UTC, SergeyMont commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        //final Exception exception= assertThrows(MethodArgumentNotValidException.class, () ->
fix

2022-04-26 20:28 UTC, kukolev approved these changes

2022-05-01 19:11 UTC, merged