RESTfull API
SergeyMont/java-filmorate pull request #3
Opened 2022-05-05 14:40 UTC by SergeyMont

2022-05-08 07:27 UTC, kukolev requested changes

2022-05-08 07:27 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse(
По моему смотрится странно. Лучше написать код на одной строке, так код будет читаться легче.

2022-05-08 07:27 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse(
По моему смотрится странно. Лучше написать код на одной строке, так код будет читаться легче.

2022-05-08 07:27 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Объект LocalDate.of(1895, 12, 28) лучше сделать константой, чтобы не приходилось всякий раз создавать при валидации.

2022-05-08 07:27 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Set<User>set=new HashSet<>();
Нарушение требований кодстайла: Не хватает пробела до и после «=». Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-05-08 07:27 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private  static Long storageId=1L;
Нарушение кодстайла: Лишний пробел после «private». Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

Нарушение требований кодстайла: Не хватает пробела до и после «=». Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-05-08 07:27 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +//package ru.yandex.practicum.filmorate.controller;
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-05-13 12:15 UTC, SergeyMont commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse(
fix

2022-05-13 12:15 UTC, SergeyMont commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse(
fix

2022-05-13 12:19 UTC, SergeyMont commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
fix

2022-05-13 12:28 UTC, SergeyMont commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +//package ru.yandex.practicum.filmorate.controller;
Solve problem with use @Data and @Builder in Film.class

2022-05-13 12:28 UTC, SergeyMont commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private  static Long storageId=1L;
fix

2022-05-13 12:29 UTC, SergeyMont commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Set<User>set=new HashSet<>();
fix

2022-05-13 20:12 UTC, kukolev approved these changes

2022-05-16 18:45 UTC, merged