feat: connect to DB, add Genres, Mpa and Likes to Film.
SergeyMont/java-filmorate pull request #5
Opened 2022-06-19 19:51 UTC by SergeyMont

2022-06-20 17:23 UTC, kukolev requested changes

2022-06-20 17:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    //@JsonSerialize(using = CustomTimeSerializer.class)
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-06-20 17:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDaoImpl.java
> +        final String query = "SELECT * FROM film LEFT JOIN mpa ON film.mpa_id = mpa.mpa_id";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-06-20 17:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDaoImpl.java
> +        String query = "SELECT * FROM genres";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-06-20 17:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/MpaDaoImpl.java
> +        String query = "SELECT * FROM mpa";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-06-20 17:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDaoImpl.java
> +        String query = "select user_id, email, login, name, birthday from users";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Также нужно поправить стиль запросов, чтобы совпадало с остальными в других классах.

Аналогично нужно поправить ниже.

2022-06-22 17:58 UTC, SergeyMont commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    //@JsonSerialize(using = CustomTimeSerializer.class)
fix

2022-06-22 17:58 UTC, SergeyMont commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDaoImpl.java
> +        final String query = "SELECT * FROM film LEFT JOIN mpa ON film.mpa_id = mpa.mpa_id";
fix

2022-06-22 17:58 UTC, SergeyMont commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDaoImpl.java
> +        String query = "SELECT * FROM genres";
fix

2022-06-22 17:58 UTC, SergeyMont commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/MpaDaoImpl.java
> +        String query = "SELECT * FROM mpa";
fix

2022-06-22 17:59 UTC, SergeyMont commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDaoImpl.java
> +        String query = "select user_id, email, login, name, birthday from users";
fix

2022-06-22 22:25 UTC, kukolev approved these changes

2022-06-28 09:42 UTC, merged